#!/usr/bin/env python3
"""
Performance Sequencer: the single playback clock for Logos's Text-to-
Performance pipeline (TTP v2).

Merges the old audio_and_face_playback.py + arm_playback_node.py into one
node so every modality (speech audio, face, arms, future tracks) is
sequenced off the same cue queue instead of guessing at each other's
timing.

Cues arrive as:
- /face/tts_chunk (SpeechData): audio + text + emoji chunks from the
  performance director (tts_action_server). Audio is the master clock.
- /face/emoji_command (String JSON): silent face cues, {"emoji": ...,
  "duration": ..., "text": ...}.
- /arm/emoji_command (String JSON): arm-only cues, same payload.

Face animation sources, in order of preference at cue play time:
1. A track delivered on /performance/face_track (String JSON) by the
   animator node — generated by the tiny face model (or its saved store).
   Payload: {"cue_id", "source", "status": "partial|complete|failed",
   "frames": [sparse semantic frames], "emoji", "text"}.
2. The semantic face LUT (animations/face_semantic/) by emoji.
3. Nothing (audio still plays; we just wait out the duration).

Arms follow the identical pattern (same shape, different topic/LUT/model)
now that the tiny arm model has landed:
1. A track delivered on /performance/arm_track (String JSON) by
   arm_animator_node.py.
2. The semantic arm LUT (animations/arms_semantic/) by emoji.
3. Nothing (arms just hold their last pose for the cue's duration).

Both run on their own timing channel -- arms start aligned with their cue
instead of blocking face/audio -- but share the same dynamic-join logic:
frames are the sparse semantic format, expanded leniently (carry-forward +
clamping) and published to the typed runtime topics, spread evenly across
the cue duration. A streamed track may join mid-cue (before
~switch_threshold of the duration has elapsed); after that the LUT
cold-open plays out undisturbed.
"""

import json
import threading
import time
from queue import Queue, Empty

import numpy as np
import rospy
import sounddevice as sd

from logos_msgs.msg import (
    SpeechData,
    EyeGazeX,
    EyeGazeY,
    EyeScaleX,
    EyeScaleY,
    EyeLidHeight,
    EyeLidAngle,
    EyeColor,
    AudioWave,
    MouthSine,
    ArmPose,
)
from std_msgs.msg import String, Bool

from performance_lib import chunking, luts
from performance_lib.face_schema import EYE_KEYS, EYE_STATE_BY_KEY, MAX_FRAMES
from performance_lib.face_gen_client import FrameExpander, expand_frames_lenient
from performance_lib.arm_gen_client import (
    MAX_ACCEPTED_FRAMES as ARM_MAX_ACCEPTED_FRAMES,
    ArmFrameExpander,
    expand_frames_lenient as expand_arm_frames_lenient,
)

EYE_MSG_BY_STATE = {
    "EyeGazeX": EyeGazeX,
    "EyeGazeY": EyeGazeY,
    "EyeScaleX": EyeScaleX,
    "EyeScaleY": EyeScaleY,
    "EyeLidHeight": EyeLidHeight,
    "EyeLidAngle": EyeLidAngle,
    "EyeColor": EyeColor,
}


class Cue:
    """One playable unit: optional audio + optional face/arm animation."""

    def __init__(self, cue_id="", text="", emoji="", duration=0.5,
                 audio_data=None, sample_rate=0, chunk_index=0, total_chunks=0,
                 face=True, arms=True, expect_track=False):
        self.cue_id = cue_id
        self.text = text
        self.emoji = emoji
        self.duration = duration
        self.audio_data = audio_data if audio_data is not None else []
        self.sample_rate = sample_rate
        self.chunk_index = chunk_index
        self.total_chunks = total_chunks  # 0 => not part of a TTS stream
        self.face = face
        self.arms = arms
        # expect_track: a silent cue that should wait (bounded) for the
        # animator's face track instead of falling straight through to the
        # LUT. TTS cues never set this -- speech never blocks on generation.
        self.expect_track = expect_track


class ArmCue:
    """One playable arm-channel unit, independent of the face/audio cue timing."""

    def __init__(self, cue_id="", emoji="", text="", duration=2.0, expect_track=False):
        self.cue_id = cue_id
        self.emoji = emoji
        self.text = text
        self.duration = duration
        # Direct arm commands with a cue_id (e.g. gesture()) wait (bounded)
        # for the animator's track; TTS-driven arm cues never do -- speech
        # never blocks on generation, the LUT cold-open covers lateness.
        self.expect_track = expect_track


class TrackStore:
    """Animator-delivered tracks (face or arm), keyed by cue_id."""

    def __init__(self):
        self._tracks = {}
        self._done = []  # recently played cue_ids; late tracks are dropped
        self._lock = threading.Lock()

    def mark_done(self, cue_id):
        with self._lock:
            self._done.append(cue_id)
            if len(self._done) > 256:
                self._done = self._done[-128:]

    def update(self, payload):
        cue_id = payload.get("cue_id")
        if not cue_id:
            return
        with self._lock:
            if cue_id in self._done:
                return
            track = self._tracks.setdefault(
                cue_id, {"frames": [], "status": "partial", "source": ""})
            frames = payload.get("frames")
            if frames is not None:
                if payload.get("append"):
                    track["frames"].extend(frames)
                else:
                    track["frames"] = frames
            track["status"] = payload.get("status", track["status"])
            track["source"] = payload.get("source", track["source"])

    def get(self, cue_id):
        with self._lock:
            track = self._tracks.get(cue_id)
            return dict(track) if track else None

    def pop(self, cue_id):
        with self._lock:
            return self._tracks.pop(cue_id, None)


class PerformanceSequencerNode:
    def __init__(self):
        rospy.init_node('performance_sequencer_node', anonymous=False)

        self.face_lut = luts.load_semantic_face_lut(
            rospy.get_param('~face_lut_dir', luts.DEFAULT_FACE_SEMANTIC_DIR))
        self.arm_lut = luts.load_semantic_arm_lut(
            rospy.get_param('~arm_lut_dir', luts.DEFAULT_ARM_SEMANTIC_DIR))
        rospy.loginfo("Sequencer LUTs: %d face (semantic), %d arm (semantic)",
                      len(self.face_lut), len(self.arm_lut))

        self.cue_queue = Queue()
        self.arm_queue = Queue()
        self.face_tracks = TrackStore()
        self.arm_tracks = TrackStore()

        self.face_pubs = {
            state: rospy.Publisher('face/' + topic, EYE_MSG_BY_STATE[state], queue_size=10)
            for state, topic in [
                ('EyeGazeX', 'eye_gaze_x'),
                ('EyeGazeY', 'eye_gaze_y'),
                ('EyeScaleX', 'eye_scale_x'),
                ('EyeScaleY', 'eye_scale_y'),
                ('EyeLidHeight', 'eye_lid_height'),
                ('EyeLidAngle', 'eye_lid_angle'),
                ('EyeColor', 'eye_color'),
            ]
        }
        self.mouth_pub = rospy.Publisher('face/mouth/sine_wave', MouthSine, queue_size=10)
        self.audio_wave_pub = rospy.Publisher('/face/mouth/audio_wave', AudioWave, queue_size=10)
        self.arm_pub = rospy.Publisher('/arm/command', ArmPose, queue_size=10)
        self.is_speaking_pub = rospy.Publisher('/tts/is_speaking', Bool, queue_size=1, latch=True)
        self.cue_done_pub = rospy.Publisher('/performance/cue_done', String, queue_size=20)
        self.track_wait_s = float(rospy.get_param('~track_wait_s', 15.0))
        # Streamed generated frames may replace LUT playback mid-cue, but only
        # before this fraction of the cue has elapsed (late switches look bad).
        self.switch_threshold = float(rospy.get_param('~switch_threshold', 0.6))

        rospy.Subscriber('/face/tts_chunk', SpeechData, self.tts_chunk_cb)
        rospy.Subscriber('/face/emoji_command', String, self.face_command_cb)
        rospy.Subscriber('/arm/emoji_command', String, self.arm_command_cb)
        rospy.Subscriber('/performance/face_track', String, self.face_track_cb)
        rospy.Subscriber('/performance/arm_track', String, self.arm_track_cb)

        self.arm_thread = threading.Thread(target=self.arm_channel_loop, daemon=True)
        self.arm_thread.start()

        rospy.loginfo("Performance Sequencer online.")

    # ─── Inputs ──────────────────────────────────────────────────────

    def tts_chunk_cb(self, msg):
        cue = Cue(
            cue_id=getattr(msg, 'cue_id', ''),
            text=msg.text_snippet,
            emoji=msg.emoji,
            duration=msg.duration,
            audio_data=msg.audio_data,
            sample_rate=msg.sample_rate,
            chunk_index=msg.current_chunk_index,
            total_chunks=msg.total_chunks,
        )
        self.cue_queue.put(cue)

    def _parse_command(self, msg, default_duration):
        data = json.loads(msg.data)
        emoji = data.get("emoji", "")
        text = data.get("text", "")
        duration = float(data.get("duration", default_duration))
        cue_id = data.get("cue_id", "")
        return emoji, text, duration, cue_id

    def face_command_cb(self, msg):
        """Silent face cue. `text` may be emoji, prose, or both in one string."""
        try:
            emoji, text, duration, cue_id = self._parse_command(msg, 1.0)
            if not emoji and not text and not cue_id:
                return
            if not emoji:
                emoji = chunking.find_emoji(text, self.face_lut.keys()) or ""
            expect_track = bool(json.loads(msg.data).get("expect_track", False))
            self.cue_queue.put(Cue(cue_id=cue_id, text=text, emoji=emoji,
                                   duration=duration, arms=False,
                                   expect_track=expect_track))
            rospy.loginfo("Queued face cue: %s%s for %.1fs",
                          emoji, (" '" + text + "'") if text else "", duration)
        except (ValueError, json.JSONDecodeError) as e:
            rospy.logerr("Bad /face/emoji_command payload: %s (%s)", msg.data, e)

    def arm_command_cb(self, msg):
        """Arm cue. `text` may be emoji, prose, or both in one string."""
        try:
            emoji, text, duration, cue_id = self._parse_command(msg, 2.0)
            if not emoji and not text and not cue_id:
                return
            if not emoji:
                emoji = chunking.find_emoji(text, self.arm_lut.keys()) or ""
            expect_track = bool(json.loads(msg.data).get("expect_track", False))
            self.arm_queue.put(ArmCue(cue_id=cue_id, emoji=emoji, text=text,
                                      duration=duration, expect_track=expect_track))
            rospy.loginfo("Queued arm cue: %s%s for %.1fs",
                          emoji, (" '" + text + "'") if text else "", duration)
        except (ValueError, json.JSONDecodeError) as e:
            rospy.logerr("Bad /arm/emoji_command payload: %s (%s)", msg.data, e)

    def face_track_cb(self, msg):
        try:
            self.face_tracks.update(json.loads(msg.data))
        except json.JSONDecodeError as e:
            rospy.logerr("Bad /performance/face_track payload: %s", e)

    def arm_track_cb(self, msg):
        try:
            self.arm_tracks.update(json.loads(msg.data))
        except json.JSONDecodeError as e:
            rospy.logerr("Bad /performance/arm_track payload: %s", e)

    # ─── Track resolution (shared by face & arm channels) ─────────────

    @staticmethod
    def _track_usable(track):
        return bool(track and track["frames"] and track["status"] != "failed")

    def _wait_for_track(self, store, cue_id, label="track"):
        """Bounded wait for an animator track (silent expect_track cues only)."""
        deadline = time.time() + self.track_wait_s
        while time.time() < deadline and not rospy.is_shutdown():
            track = store.get(cue_id)
            # status "lut" = animator's explicit "play your own LUT" signal
            if track and (track["frames"] or track["status"] in ("failed", "lut")):
                return track
            rospy.sleep(0.1)
        rospy.logwarn("Timed out waiting %.1fs for %s %s; falling back.",
                      self.track_wait_s, label, cue_id)
        return store.get(cue_id)

    # ─── Face resolution & playback ──────────────────────────────────

    def publish_face_pose(self, pose, step_duration):
        """Publish one expanded full pose to the typed face topics."""
        left, right = pose["eyes"]["left"], pose["eyes"]["right"]
        for key in EYE_KEYS:
            state = EYE_STATE_BY_KEY[key]
            pub = self.face_pubs[state]
            if left[key] == right[key]:
                sides = [("both", left[key])]
            else:
                sides = [("left", left[key]), ("right", right[key])]
            for side, value in sides:
                m = EYE_MSG_BY_STATE[state](**{"eye_side": side, key: value})
                m.duration = step_duration
                pub.publish(m)
        mouth = MouthSine(**pose["mouth"])
        mouth.duration = max(0.05, step_duration)
        self.mouth_pub.publish(mouth)

    def _sleep_slices(self, seconds):
        """Sleep in small slices so shutdown stays responsive."""
        end = time.time() + seconds
        while not rospy.is_shutdown() and time.time() < end:
            rospy.sleep(min(0.05, max(0.0, end - time.time())))

    def play_face_for_cue(self, cue):
        """
        Dynamic face playback over the cue's duration.

        Starts on the LUT (cold open) when the emoji has one; if an animator
        track (possibly still streaming in, frame by frame) shows up before
        ~switch_threshold of the cue has elapsed, playback switches to it and
        paces the remaining generated frames over the remaining time. Holds
        the last pose when a stream stalls. Always consumes the cue duration.
        """
        track = self.face_tracks.get(cue.cue_id) if cue.cue_id else None
        if cue.expect_track and not self._track_usable(track):
            track = self._wait_for_track(self.face_tracks, cue.cue_id, label="face track")

        t0 = time.time()
        t_end = t0 + max(0.1, cue.duration)

        lut_poses = None
        if cue.emoji and cue.emoji in self.face_lut:
            lut_poses = expand_frames_lenient(self.face_lut[cue.emoji]["frames"])
        lut_step = (max(0.1, cue.duration) / len(lut_poses)) if lut_poses else 0.0
        lut_idx = 0

        mode = None  # None -> undecided/lut, "track" -> animator frames
        expander = None
        track_played = 0

        if not lut_poses and not cue.cue_id and (cue.emoji or cue.text):
            rospy.logwarn_throttle(
                5, "No face animation available for '%s%s'.", cue.emoji, cue.text)

        while not rospy.is_shutdown():
            now = time.time()
            if now >= t_end:
                break

            if mode != "track" and cue.cue_id:
                track = self.face_tracks.get(cue.cue_id)
                if self._track_usable(track):
                    progress = (now - t0) / (t_end - t0)
                    if progress < self.switch_threshold or lut_idx == 0:
                        mode = "track"
                        expander = FrameExpander()
                        rospy.loginfo(
                            "Cue %s: face from %s (join at %d%%)",
                            cue.cue_id, track.get("source") or "animator",
                            int(progress * 100))

            if mode == "track":
                track = self.face_tracks.get(cue.cue_id) or track
                frames = track["frames"] if track else []
                if track_played < len(frames):
                    if track.get("status") == "complete":
                        est_remaining = len(frames) - track_played
                    else:
                        # stream in flight: assume a mid-sized sequence so
                        # early frames don't hog the whole cue
                        est_total = min(MAX_FRAMES, max(len(frames) + 2, 6))
                        est_remaining = est_total - track_played
                    step = max(0.05, (t_end - now) / max(1, est_remaining))
                    pose = expander.feed(frames[track_played])
                    track_played += 1
                    if pose:
                        self.publish_face_pose(pose, step)
                    self._sleep_slices(min(step, t_end - time.time()))
                else:
                    # stream stall or all frames shown: hold last pose
                    rospy.sleep(0.05)
            elif lut_poses:
                if lut_idx < len(lut_poses):
                    self.publish_face_pose(lut_poses[lut_idx], lut_step)
                    lut_idx += 1
                    self._sleep_slices(min(lut_step, t_end - time.time()))
                else:
                    rospy.sleep(0.05)
            else:
                # nothing to show (yet); idle out the duration
                rospy.sleep(0.05)

    # ─── Arm channel ─────────────────────────────────────────────────

    def arm_channel_loop(self):
        while not rospy.is_shutdown():
            try:
                arm_cue = self.arm_queue.get(timeout=0.25)
            except Empty:
                continue
            self.play_arms_for_cue(arm_cue)

    def publish_arm_pose(self, pose):
        """Publish one expanded full arm pose to /arm/command (joint1/joint2 wire names)."""
        left, right = pose["arms"]["left"], pose["arms"]["right"]
        sides = [("both", left)] if left == right else [("left", left), ("right", right)]
        for side, p in sides:
            self.arm_pub.publish(ArmPose(
                side=side, joint1=p["shoulder_roll"], joint2=p["shoulder_pitch"], wrist=p["wrist"]))

    def play_arms_for_cue(self, arm_cue):
        """
        Dynamic arm playback over the cue's duration -- the arm-channel twin
        of play_face_for_cue(). Starts on the LUT (cold open) when the emoji
        has one; if an animator track shows up before ~switch_threshold of
        the cue has elapsed, playback switches to it. Idles out the duration
        if nothing is available (arms just hold their last pose).
        """
        track = self.arm_tracks.get(arm_cue.cue_id) if arm_cue.cue_id else None
        if arm_cue.expect_track and not self._track_usable(track):
            track = self._wait_for_track(self.arm_tracks, arm_cue.cue_id, label="arm track")

        t0 = time.time()
        t_end = t0 + max(0.1, arm_cue.duration)

        lut_poses = None
        if arm_cue.emoji and arm_cue.emoji in self.arm_lut:
            lut_poses = expand_arm_frames_lenient(self.arm_lut[arm_cue.emoji]["frames"])
        lut_step = (max(0.1, arm_cue.duration) / len(lut_poses)) if lut_poses else 0.0
        lut_idx = 0

        mode = None  # None -> undecided/lut, "track" -> animator frames
        expander = None
        track_played = 0

        while not rospy.is_shutdown():
            now = time.time()
            if now >= t_end:
                break

            if mode != "track" and arm_cue.cue_id:
                track = self.arm_tracks.get(arm_cue.cue_id)
                if self._track_usable(track):
                    progress = (now - t0) / (t_end - t0)
                    if progress < self.switch_threshold or lut_idx == 0:
                        mode = "track"
                        expander = ArmFrameExpander()
                        rospy.loginfo(
                            "Arm cue %s: from %s (join at %d%%)",
                            arm_cue.cue_id, track.get("source") or "animator",
                            int(progress * 100))

            if mode == "track":
                track = self.arm_tracks.get(arm_cue.cue_id) or track
                frames = track["frames"] if track else []
                if track_played < len(frames):
                    if track.get("status") == "complete":
                        est_remaining = len(frames) - track_played
                    else:
                        est_total = min(ARM_MAX_ACCEPTED_FRAMES, max(len(frames) + 2, 4))
                        est_remaining = est_total - track_played
                    step = max(0.05, (t_end - now) / max(1, est_remaining))
                    pose = expander.feed(frames[track_played])
                    track_played += 1
                    if pose:
                        self.publish_arm_pose(pose)
                    self._sleep_slices(min(step, t_end - time.time()))
                else:
                    rospy.sleep(0.05)
            elif lut_poses:
                if lut_idx < len(lut_poses):
                    self.publish_arm_pose(lut_poses[lut_idx])
                    lut_idx += 1
                    self._sleep_slices(min(lut_step, t_end - time.time()))
                else:
                    rospy.sleep(0.05)
            else:
                rospy.sleep(0.05)

    # ─── Audio ───────────────────────────────────────────────────────

    def play_audio(self, audio_data, sample_rate):
        try:
            if sample_rate <= 0:
                sample_rate = 22050
            self.is_speaking_pub.publish(Bool(data=True))
            audio_array = np.array(audio_data, dtype=np.int16)
            sd.play(audio_array, samplerate=sample_rate)
            sd.wait()
        except Exception as e:
            rospy.logerr("Error playing audio: %s", e)

    # ─── Cue execution ───────────────────────────────────────────────

    def process_cue(self, cue):
        has_audio = len(cue.audio_data) > 0

        if has_audio and cue.sample_rate > 0:
            wave = AudioWave()
            wave.data = cue.audio_data
            wave.sample_rate = cue.sample_rate
            self.audio_wave_pub.publish(wave)

        audio_thread = None
        if has_audio:
            sr = cue.sample_rate if cue.sample_rate > 0 else 22050
            audio_thread = threading.Thread(
                target=self.play_audio, args=(cue.audio_data, sr))
            audio_thread.start()

        # Arms start aligned with the cue, on their own channel. TTS-driven
        # arm cues never wait for a track (expect_track=False) -- speech
        # never blocks on generation, same rule as the face channel.
        if cue.arms:
            self.arm_queue.put(ArmCue(cue_id=cue.cue_id, emoji=cue.emoji, text=cue.text,
                                      duration=cue.duration, expect_track=False))

        if cue.face:
            self.play_face_for_cue(cue)
        elif cue.duration > 0 and not has_audio:
            rospy.sleep(cue.duration)

        if audio_thread:
            audio_thread.join()

        if cue.cue_id:
            self.face_tracks.pop(cue.cue_id)
            self.face_tracks.mark_done(cue.cue_id)
            self.arm_tracks.pop(cue.cue_id)
            self.arm_tracks.mark_done(cue.cue_id)
            self.cue_done_pub.publish(String(data=json.dumps({"cue_id": cue.cue_id})))

        # End of a TTS stream: clear the speaking flag after the last chunk.
        if cue.total_chunks > 0 and cue.chunk_index == cue.total_chunks - 1:
            rospy.loginfo("Speech sequence finished. Clearing is_speaking flag.")
            self.is_speaking_pub.publish(Bool(data=False))

    def run(self):
        while not rospy.is_shutdown():
            try:
                cue = self.cue_queue.get(timeout=0.05)
            except Empty:
                continue
            self.process_cue(cue)


def main():
    try:
        node = PerformanceSequencerNode()
        node.run()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
