#!/usr/bin/env python3
"""
Performance Sequencer: the single playback clock for Logos's Text-to-
Performance pipeline (TTP v2).

Merges the old audio_and_face_playback.py + arm_playback_node.py into one
node so every modality (speech audio, face, arms, future tracks) is
sequenced off the same cue queue instead of guessing at each other's
timing.

Cues arrive as:
- /face/tts_chunk (SpeechData): audio + text + emoji chunks from the
  performance director (tts_action_server). Audio is the master clock.
- /face/emoji_command (String JSON): silent face cues, {"emoji": ...,
  "duration": ..., "text": ...}.
- /arm/emoji_command (String JSON): arm-only cues, same payload.

Face animation sources, in order of preference at cue play time:
1. A track delivered on /performance/face_track (String JSON) by the
   animator node — generated by the tiny face model (or its saved store).
   Payload: {"cue_id", "source", "status": "partial|complete|failed",
   "frames": [sparse semantic frames], "emoji", "text"}.
2. The semantic face LUT (animations/face_semantic/) by emoji.
3. Nothing (audio still plays; we just wait out the duration).

Face frames are the sparse semantic format; they are expanded leniently
(carry-forward + clamping) and published to the existing typed face topics,
spread evenly across the cue duration, exactly like the legacy player did.
Arms remain legacy-format LUT playback on a parallel channel that starts
aligned with its cue instead of the old qsize-based wall-clock guess.
"""

import json
import threading
import time
from queue import Queue, Empty

import numpy as np
import rospy
import sounddevice as sd

from logos_msgs.msg import (
    SpeechData,
    EyeGazeX,
    EyeGazeY,
    EyeScaleX,
    EyeScaleY,
    EyeLidHeight,
    EyeLidAngle,
    EyeColor,
    AudioWave,
    MouthSine,
    ArmPose,
)
from std_msgs.msg import String, Bool

from performance_lib import luts
from performance_lib.face_schema import EYE_KEYS, EYE_STATE_BY_KEY
from performance_lib.face_gen_client import expand_frames_lenient

EYE_MSG_BY_STATE = {
    "EyeGazeX": EyeGazeX,
    "EyeGazeY": EyeGazeY,
    "EyeScaleX": EyeScaleX,
    "EyeScaleY": EyeScaleY,
    "EyeLidHeight": EyeLidHeight,
    "EyeLidAngle": EyeLidAngle,
    "EyeColor": EyeColor,
}


class Cue:
    """One playable unit: optional audio + optional face/arm animation."""

    def __init__(self, cue_id="", text="", emoji="", duration=0.5,
                 audio_data=None, sample_rate=0, chunk_index=0, total_chunks=0,
                 face=True, arms=True):
        self.cue_id = cue_id
        self.text = text
        self.emoji = emoji
        self.duration = duration
        self.audio_data = audio_data if audio_data is not None else []
        self.sample_rate = sample_rate
        self.chunk_index = chunk_index
        self.total_chunks = total_chunks  # 0 => not part of a TTS stream
        self.face = face
        self.arms = arms


class FaceTrackStore:
    """Animator-delivered face tracks, keyed by cue_id."""

    def __init__(self):
        self._tracks = {}
        self._lock = threading.Lock()

    def update(self, payload):
        cue_id = payload.get("cue_id")
        if not cue_id:
            return
        with self._lock:
            track = self._tracks.setdefault(
                cue_id, {"frames": [], "status": "partial", "source": ""})
            frames = payload.get("frames")
            if frames is not None:
                if payload.get("append"):
                    track["frames"].extend(frames)
                else:
                    track["frames"] = frames
            track["status"] = payload.get("status", track["status"])
            track["source"] = payload.get("source", track["source"])

    def get(self, cue_id):
        with self._lock:
            track = self._tracks.get(cue_id)
            return dict(track) if track else None

    def pop(self, cue_id):
        with self._lock:
            return self._tracks.pop(cue_id, None)


class PerformanceSequencerNode:
    def __init__(self):
        rospy.init_node('performance_sequencer_node', anonymous=False)

        self.face_lut = luts.load_semantic_face_lut(
            rospy.get_param('~face_lut_dir', luts.DEFAULT_FACE_SEMANTIC_DIR))
        self.arm_lut = luts.load_arm_lut(
            rospy.get_param('~arm_lut_dir', luts.DEFAULT_ARM_DIR))
        rospy.loginfo("Sequencer LUTs: %d face (semantic), %d arm (legacy)",
                      len(self.face_lut), len(self.arm_lut))

        self.cue_queue = Queue()
        self.arm_queue = Queue()
        self.face_tracks = FaceTrackStore()

        self.face_pubs = {
            state: rospy.Publisher('face/' + topic, EYE_MSG_BY_STATE[state], queue_size=10)
            for state, topic in [
                ('EyeGazeX', 'eye_gaze_x'),
                ('EyeGazeY', 'eye_gaze_y'),
                ('EyeScaleX', 'eye_scale_x'),
                ('EyeScaleY', 'eye_scale_y'),
                ('EyeLidHeight', 'eye_lid_height'),
                ('EyeLidAngle', 'eye_lid_angle'),
                ('EyeColor', 'eye_color'),
            ]
        }
        self.mouth_pub = rospy.Publisher('face/mouth/sine_wave', MouthSine, queue_size=10)
        self.audio_wave_pub = rospy.Publisher('/face/mouth/audio_wave', AudioWave, queue_size=10)
        self.arm_pub = rospy.Publisher('/arm/command', ArmPose, queue_size=10)
        self.is_speaking_pub = rospy.Publisher('/tts/is_speaking', Bool, queue_size=1, latch=True)

        rospy.Subscriber('/face/tts_chunk', SpeechData, self.tts_chunk_cb)
        rospy.Subscriber('/face/emoji_command', String, self.face_command_cb)
        rospy.Subscriber('/arm/emoji_command', String, self.arm_command_cb)
        rospy.Subscriber('/performance/face_track', String, self.face_track_cb)

        self.arm_thread = threading.Thread(target=self.arm_channel_loop, daemon=True)
        self.arm_thread.start()

        rospy.loginfo("Performance Sequencer online.")

    # ─── Inputs ──────────────────────────────────────────────────────

    def tts_chunk_cb(self, msg):
        cue = Cue(
            cue_id=getattr(msg, 'cue_id', ''),
            text=msg.text_snippet,
            emoji=msg.emoji,
            duration=msg.duration,
            audio_data=msg.audio_data,
            sample_rate=msg.sample_rate,
            chunk_index=msg.current_chunk_index,
            total_chunks=msg.total_chunks,
        )
        self.cue_queue.put(cue)

    def _parse_command(self, msg, default_duration):
        data = json.loads(msg.data)
        emoji = data.get("emoji", "")
        text = data.get("text", "")
        duration = float(data.get("duration", default_duration))
        cue_id = data.get("cue_id", "")
        return emoji, text, duration, cue_id

    def face_command_cb(self, msg):
        """Silent face cue. Accepts any text, not just a known emoji."""
        try:
            emoji, text, duration, cue_id = self._parse_command(msg, 1.0)
            if not emoji and not text and not cue_id:
                return
            self.cue_queue.put(Cue(cue_id=cue_id, text=text, emoji=emoji,
                                   duration=duration, arms=False))
            rospy.loginfo("Queued face cue: %s%s for %.1fs",
                          emoji, (" '" + text + "'") if text else "", duration)
        except (ValueError, json.JSONDecodeError) as e:
            rospy.logerr("Bad /face/emoji_command payload: %s (%s)", msg.data, e)

    def arm_command_cb(self, msg):
        """Arm-only cue; goes straight to the arm channel."""
        try:
            emoji, text, duration, _ = self._parse_command(msg, 2.0)
            frames = self.arm_lut.get(emoji)
            if not frames:
                rospy.logwarn("Arm command for '%s%s': no arm preset found.", emoji, text)
                return
            self.arm_queue.put((frames, duration))
        except (ValueError, json.JSONDecodeError) as e:
            rospy.logerr("Bad /arm/emoji_command payload: %s (%s)", msg.data, e)

    def face_track_cb(self, msg):
        try:
            self.face_tracks.update(json.loads(msg.data))
        except json.JSONDecodeError as e:
            rospy.logerr("Bad /performance/face_track payload: %s", e)

    # ─── Face resolution & playback ──────────────────────────────────

    def resolve_face_frames(self, cue):
        """Return (sparse_semantic_frames, source) for a cue, or (None, '')."""
        if cue.cue_id:
            track = self.face_tracks.get(cue.cue_id)
            if track and track["frames"] and track["status"] != "failed":
                return track["frames"], (track.get("source") or "animator")
        if cue.emoji and cue.emoji in self.face_lut:
            return self.face_lut[cue.emoji]["frames"], "lut"
        if cue.emoji or cue.text:
            rospy.logwarn_throttle(
                5, "No face animation available for '%s%s'.", cue.emoji, cue.text)
        return None, ""

    def publish_face_pose(self, pose, step_duration):
        """Publish one expanded full pose to the typed face topics."""
        left, right = pose["eyes"]["left"], pose["eyes"]["right"]
        for key in EYE_KEYS:
            state = EYE_STATE_BY_KEY[key]
            pub = self.face_pubs[state]
            if left[key] == right[key]:
                sides = [("both", left[key])]
            else:
                sides = [("left", left[key]), ("right", right[key])]
            for side, value in sides:
                m = EYE_MSG_BY_STATE[state](**{"eye_side": side, key: value})
                m.duration = step_duration
                pub.publish(m)
        mouth = MouthSine(**pose["mouth"])
        mouth.duration = max(0.05, step_duration)
        self.mouth_pub.publish(mouth)

    def play_face(self, sparse_frames, duration):
        poses = expand_frames_lenient(sparse_frames)
        if not poses:
            return
        step = max(0.05, duration / len(poses))
        for pose in poses:
            self.publish_face_pose(pose, step)
            rospy.sleep(step)

    # ─── Arm channel ─────────────────────────────────────────────────

    def arm_channel_loop(self):
        while not rospy.is_shutdown():
            try:
                frames, duration = self.arm_queue.get(timeout=0.25)
            except Empty:
                continue
            self.play_arms(frames, duration)

    def play_arms(self, frames, duration):
        if not frames:
            return
        step = duration / len(frames)
        for keyframe in frames:
            for action in keyframe:
                try:
                    if action['state'] == "ArmPose":
                        self.arm_pub.publish(ArmPose(**action['parameters']))
                    else:
                        rospy.logwarn_throttle(5, "Unknown arm action: %s", action['state'])
                except Exception as e:
                    rospy.logerr("Error publishing ArmPose: %s", e)
            rospy.sleep(step)

    # ─── Audio ───────────────────────────────────────────────────────

    def play_audio(self, audio_data, sample_rate):
        try:
            if sample_rate <= 0:
                sample_rate = 22050
            self.is_speaking_pub.publish(Bool(data=True))
            audio_array = np.array(audio_data, dtype=np.int16)
            sd.play(audio_array, samplerate=sample_rate)
            sd.wait()
        except Exception as e:
            rospy.logerr("Error playing audio: %s", e)

    # ─── Cue execution ───────────────────────────────────────────────

    def process_cue(self, cue):
        has_audio = len(cue.audio_data) > 0

        if has_audio and cue.sample_rate > 0:
            wave = AudioWave()
            wave.data = cue.audio_data
            wave.sample_rate = cue.sample_rate
            self.audio_wave_pub.publish(wave)

        audio_thread = None
        if has_audio:
            sr = cue.sample_rate if cue.sample_rate > 0 else 22050
            audio_thread = threading.Thread(
                target=self.play_audio, args=(cue.audio_data, sr))
            audio_thread.start()

        # Arms start aligned with the cue, on their own channel.
        if cue.arms and cue.emoji and cue.emoji in self.arm_lut:
            self.arm_queue.put((self.arm_lut[cue.emoji], cue.duration))

        if cue.face:
            frames, source = self.resolve_face_frames(cue)
            if frames:
                if source != "lut":
                    rospy.loginfo("Cue %s face from %s (%d frames)",
                                  cue.cue_id or cue.emoji, source, len(frames))
                self.play_face(frames, cue.duration)
            elif cue.duration > 0:
                rospy.sleep(cue.duration)
        elif cue.duration > 0 and not has_audio:
            rospy.sleep(cue.duration)

        if audio_thread:
            audio_thread.join()

        if cue.cue_id:
            self.face_tracks.pop(cue.cue_id)

        # End of a TTS stream: clear the speaking flag after the last chunk.
        if cue.total_chunks > 0 and cue.chunk_index == cue.total_chunks - 1:
            rospy.loginfo("Speech sequence finished. Clearing is_speaking flag.")
            self.is_speaking_pub.publish(Bool(data=False))

    def run(self):
        while not rospy.is_shutdown():
            try:
                cue = self.cue_queue.get(timeout=0.05)
            except Empty:
                continue
            self.process_cue(cue)


def main():
    try:
        node = PerformanceSequencerNode()
        node.run()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
