#!/usr/bin/env python3
"""
Performance Sequencer: the single playback clock for Logos's Text-to-
Performance pipeline (TTP v3).

Merges the old audio_and_face_playback.py + arm_playback_node.py into one
node so every modality (speech audio, face, arms, future tracks) is
sequenced off the same cue queue instead of guessing at each other's
timing.

TTP v3 provisional cue timeline: TTS cues enter the queue at *announce*
time (/performance/cue_announce, published by the director before any
synthesis) carrying est_duration as a provisional clock. Audio
(/face/tts_chunk SpeechData) attaches to its pending cue whenever it
lands and becomes the master clock the moment it exists. While a cue is
next to play but its audio is still synthesizing, the sequencer stages
the first face/arm frame -- a held pose, an actor hitting the mark -- and
nothing else animates until speech actually starts. Audio later than
~audio_wait_s plays out silently on est_duration rather than wedging the
queue. /performance/cue_playing fires the moment a cue's audio (or silent
playout) actually starts -- that's the caption/choreography sync point.

Cues arrive as:
- /performance/cue_announce (String JSON): TTS cue skeletons, pre-audio.
- /face/tts_chunk (SpeechData): the audio for an announced cue (also the
  legacy full-cue path for publishers that never announce).
- /face/emoji_command (String JSON): silent face cues, {"emoji": ...,
  "duration": ..., "text": ...}.
- /arm/emoji_command (String JSON): arm-only cues, same payload.

Animation per channel (face and arms share one playback helper):
1. A track delivered on /performance/face_track // /performance/arm_track
   (String JSON) by the animator nodes -- generated by the tiny models,
   their saved stores, or the animator's own LUT fallback. Payload:
   {"cue_id", "source", "status": "partial|complete|failed|lut",
   "frames": [sparse semantic frames]}. Frames may stream in mid-cue;
   pacing re-stretches over the remaining cue time every time new
   information arrives (frames or a terminal status).
2. The sequencer's own semantic LUT copy, when the animator answers
   status="lut" (pure-emoji fast path), the cascade failed, the cue has
   no cue_id (legacy commands), or no track message shows up at all by
   half the cue (animator down -- the LUT fallback must survive that).
3. Nothing (audio still plays; the last pose holds).

The v2 LUT "cold-open with mid-cue track switch" is gone (Mark's call,
2026-07-06): live generation lands in 1-2s, so the sequencer plays
whatever single track the cascade resolves instead of second-guessing
sources mid-cue.
"""

import json
import threading
import time
from queue import Queue, Empty

import numpy as np
import rospy
import sounddevice as sd

from logos_msgs.msg import (
    SpeechData,
    EyeGazeX,
    EyeGazeY,
    EyeScaleX,
    EyeScaleY,
    EyeLidHeight,
    EyeLidAngle,
    EyeColor,
    AudioWave,
    MouthSine,
    ArmPose,
)
from std_msgs.msg import String, Bool

from performance_lib import chunking, luts
from performance_lib.face_schema import EYE_KEYS, EYE_STATE_BY_KEY, MAX_FRAMES
from performance_lib.face_gen_client import FrameExpander, expand_frames_lenient
from performance_lib.arm_gen_client import (
    MAX_ACCEPTED_FRAMES as ARM_MAX_ACCEPTED_FRAMES,
    ArmFrameExpander,
    expand_frames_lenient as expand_arm_frames_lenient,
)

EYE_MSG_BY_STATE = {
    "EyeGazeX": EyeGazeX,
    "EyeGazeY": EyeGazeY,
    "EyeScaleX": EyeScaleX,
    "EyeScaleY": EyeScaleY,
    "EyeLidHeight": EyeLidHeight,
    "EyeLidAngle": EyeLidAngle,
    "EyeColor": EyeColor,
}


class Cue:
    """
    One playable unit: optional audio + optional face/arm animation.

    TTS cues are created at announce time with audio_pending=True and only
    est_duration for a clock; the SpeechData callback fills in the real
    audio + duration and sets audio_event whenever synthesis lands (which
    may be before, during, or after this cue reaches the front of the
    queue). Gestures and legacy tts_chunk cues are born complete.
    """

    def __init__(self, cue_id="", text="", emoji="", duration=0.5,
                 audio_data=None, sample_rate=0, chunk_index=0, total_chunks=0,
                 face=True, arms=True, expect_track=False, wait_timeout_s=None,
                 audio_pending=False):
        self.cue_id = cue_id
        self.text = text
        self.emoji = emoji
        self.duration = duration  # est_duration until real audio lands
        self.audio_data = audio_data if audio_data is not None else []
        self.sample_rate = sample_rate
        self.chunk_index = chunk_index
        self.total_chunks = total_chunks  # 0 => not part of a TTS stream
        self.face = face
        self.arms = arms
        # expect_track: this cue should wait (bounded) for the animator's
        # track instead of falling straight through to the LUT. Gestures
        # always set this; TTS cues only do when opted into "sync" mode
        # (performance.sync) -- otherwise speech never blocks on generation.
        self.expect_track = expect_track
        # None => node default (~track_wait_s). Sync-mode TTS cues use the
        # tighter ~sync_wait_s instead -- speech shouldn't stall as long as
        # a silent gesture reasonably can.
        self.wait_timeout_s = wait_timeout_s
        # Provisional-timeline state (TTS cues announced before synthesis)
        self.audio_pending = audio_pending
        self.audio_event = threading.Event()
        self.canceled = False


class ArmCue:
    """One playable arm-channel unit, independent of the face/audio cue timing."""

    def __init__(self, cue_id="", emoji="", text="", duration=2.0,
                 expect_track=False, wait_timeout_s=None, done_event=None):
        self.cue_id = cue_id
        self.emoji = emoji
        self.text = text
        self.duration = duration
        # Direct arm commands with a cue_id (e.g. gesture()) always wait
        # (bounded); TTS-driven arm cues only do when their parent Cue is
        # in "sync" mode -- otherwise speech never blocks on generation.
        self.expect_track = expect_track
        self.wait_timeout_s = wait_timeout_s
        # Set by the arm channel when it finishes this cue, so process_cue
        # doesn't pop/mark_done the arm track out from under a still-playing
        # arm channel (the v2 race).
        self.done_event = done_event


class TrackStore:
    """Animator-delivered tracks (face or arm), keyed by cue_id."""

    def __init__(self):
        self._tracks = {}
        self._done = []  # recently played cue_ids; late tracks are dropped
        self._lock = threading.Lock()

    def mark_done(self, cue_id):
        with self._lock:
            self._done.append(cue_id)
            if len(self._done) > 256:
                self._done = self._done[-128:]

    def is_done(self, cue_id):
        with self._lock:
            return cue_id in self._done

    def update(self, payload):
        cue_id = payload.get("cue_id")
        if not cue_id:
            return
        with self._lock:
            if cue_id in self._done:
                return
            track = self._tracks.setdefault(
                cue_id, {"frames": [], "status": "partial", "source": ""})
            frames = payload.get("frames")
            if frames is not None:
                if payload.get("append"):
                    track["frames"].extend(frames)
                else:
                    track["frames"] = frames
            track["status"] = payload.get("status", track["status"])
            track["source"] = payload.get("source", track["source"])

    def get(self, cue_id):
        with self._lock:
            track = self._tracks.get(cue_id)
            return dict(track) if track else None

    def pop(self, cue_id):
        with self._lock:
            return self._tracks.pop(cue_id, None)


class PerformanceSequencerNode:
    def __init__(self):
        rospy.init_node('performance_sequencer_node', anonymous=False)

        self.face_lut = luts.load_semantic_face_lut(
            rospy.get_param('~face_lut_dir', luts.DEFAULT_FACE_SEMANTIC_DIR))
        self.arm_lut = luts.load_semantic_arm_lut(
            rospy.get_param('~arm_lut_dir', luts.DEFAULT_ARM_SEMANTIC_DIR))
        rospy.loginfo("Sequencer LUTs: %d face (semantic), %d arm (semantic)",
                      len(self.face_lut), len(self.arm_lut))

        self.cue_queue = Queue()
        self.arm_queue = Queue()
        self.face_tracks = TrackStore()
        self.arm_tracks = TrackStore()
        # Announced-but-unsynthesized TTS cues, keyed by cue_id: the queue
        # holds the same Cue objects; tts_chunk_cb attaches audio through
        # this registry whenever synthesis lands.
        self.pending_audio = {}
        self.pending_lock = threading.Lock()

        self.face_pubs = {
            state: rospy.Publisher('face/' + topic, EYE_MSG_BY_STATE[state], queue_size=10)
            for state, topic in [
                ('EyeGazeX', 'eye_gaze_x'),
                ('EyeGazeY', 'eye_gaze_y'),
                ('EyeScaleX', 'eye_scale_x'),
                ('EyeScaleY', 'eye_scale_y'),
                ('EyeLidHeight', 'eye_lid_height'),
                ('EyeLidAngle', 'eye_lid_angle'),
                ('EyeColor', 'eye_color'),
            ]
        }
        self.mouth_pub = rospy.Publisher('face/mouth/sine_wave', MouthSine, queue_size=10)
        self.audio_wave_pub = rospy.Publisher('/face/mouth/audio_wave', AudioWave, queue_size=10)
        self.arm_pub = rospy.Publisher('/arm/command', ArmPose, queue_size=10)
        self.is_speaking_pub = rospy.Publisher('/tts/is_speaking', Bool, queue_size=1, latch=True)
        self.cue_done_pub = rospy.Publisher('/performance/cue_done', String, queue_size=20)
        # Playback-time event: fired the moment a cue's audio (or silent
        # playout) actually starts. Caption/choreography consumers key off
        # this instead of synthesis-time /face/tts_chunk.
        self.cue_playing_pub = rospy.Publisher('/performance/cue_playing', String, queue_size=20)
        self.track_wait_s = float(rospy.get_param('~track_wait_s', 15.0))
        # Sync mode: TTS cues opt in (via performance.sync) to a bounded wait
        # for the first generated frame -- same _wait_for_track() machinery
        # gestures already use, just a tighter default bound since speech
        # shouldn't stall as long as a silent gesture reasonably can.
        self.sync_wait_s = float(rospy.get_param('~sync_wait_s', 4.0))
        # Provisional timeline: how long the front-of-queue cue waits for
        # its audio (holding a staged first pose) before giving up and
        # playing out silently on est_duration -- a hung synthesis must not
        # wedge the whole queue.
        self.audio_wait_s = float(rospy.get_param('~audio_wait_s', 10.0))

        # The two playback channels share one pacing loop; these bundles are
        # the only place they differ. mid_guess: assumed in-flight sequence
        # size so early streamed frames don't hog the whole cue.
        self.face_channel = {
            "label": "face",
            "store": self.face_tracks,
            "lut": self.face_lut,
            "expander": FrameExpander,
            "expand": expand_frames_lenient,
            "publish": self.publish_face_pose,
            "mid_guess": 6,
            "max_frames": MAX_FRAMES,
        }
        self.arm_channel = {
            "label": "arms",
            "store": self.arm_tracks,
            "lut": self.arm_lut,
            "expander": ArmFrameExpander,
            "expand": expand_arm_frames_lenient,
            "publish": lambda pose, step: self.publish_arm_pose(pose),
            "mid_guess": 4,
            "max_frames": ARM_MAX_ACCEPTED_FRAMES,
        }

        rospy.Subscriber('/face/tts_chunk', SpeechData, self.tts_chunk_cb)
        rospy.Subscriber('/face/emoji_command', String, self.face_command_cb)
        rospy.Subscriber('/arm/emoji_command', String, self.arm_command_cb)
        rospy.Subscriber('/performance/face_track', String, self.face_track_cb)
        rospy.Subscriber('/performance/arm_track', String, self.arm_track_cb)
        rospy.Subscriber('/performance/cue_announce', String, self.cue_announce_cb)

        self.arm_thread = threading.Thread(target=self.arm_channel_loop, daemon=True)
        self.arm_thread.start()

        rospy.loginfo("Performance Sequencer online.")

    # ─── Inputs ──────────────────────────────────────────────────────

    def cue_announce_cb(self, msg):
        """
        TTP v3: announced cues enter the playback queue immediately, before
        any synthesis, carrying est_duration as a provisional clock and
        audio_pending=True. tts_chunk_cb attaches the real audio through
        the pending_audio registry whenever it lands. A {"canceled": true}
        announce (director goal canceled mid-synthesis) releases every
        still-pending cue of that utterance so the queue can't wedge.
        """
        try:
            announce = json.loads(msg.data)
        except json.JSONDecodeError:
            return

        utterance_id = announce.get("utterance_id", "")
        if announce.get("canceled"):
            prefix = utterance_id + ":"
            with self.pending_lock:
                for cue_id, cue in list(self.pending_audio.items()):
                    if cue_id.startswith(prefix):
                        cue.canceled = True
                        cue.audio_event.set()
                        del self.pending_audio[cue_id]
            return

        cues = announce.get("cues", [])
        sync = bool((announce.get("performance") or {}).get("sync", False))
        for spec in cues:
            cue_id = spec.get("cue_id", "")
            if not cue_id:
                continue
            cue = Cue(
                cue_id=cue_id,
                text=spec.get("text", ""),
                emoji=spec.get("emoji", ""),
                duration=float(spec.get("est_duration", 1.0)),
                chunk_index=int(spec.get("index", 0)),
                total_chunks=len(cues),
                expect_track=sync,
                wait_timeout_s=self.sync_wait_s if sync else None,
                audio_pending=True,
            )
            with self.pending_lock:
                self.pending_audio[cue_id] = cue
                if len(self.pending_audio) > 256:
                    # Defensive cap for cues announced but never resolved.
                    for stale in list(self.pending_audio)[:128]:
                        self.pending_audio.pop(stale, None)
            self.cue_queue.put(cue)

    def tts_chunk_cb(self, msg):
        cue_id = getattr(msg, 'cue_id', '')
        cue = None
        if cue_id:
            with self.pending_lock:
                cue = self.pending_audio.pop(cue_id, None)
            if cue is None and ":" in cue_id:
                # Director-format cue_id but no pending entry: the announce
                # may still be in flight on its own topic (cross-topic order
                # isn't guaranteed). Give it a beat before going legacy.
                deadline = time.time() + 0.5
                while cue is None and time.time() < deadline:
                    time.sleep(0.05)
                    with self.pending_lock:
                        cue = self.pending_audio.pop(cue_id, None)

        if cue is not None:
            # Attach real audio to the announced cue: real duration replaces
            # est_duration, and the (possibly waiting) playback thread wakes.
            cue.text = msg.text_snippet
            cue.emoji = msg.emoji
            cue.duration = msg.duration
            cue.audio_data = msg.audio_data
            cue.sample_rate = msg.sample_rate
            cue.chunk_index = msg.current_chunk_index
            cue.total_chunks = msg.total_chunks
            cue.audio_event.set()
            return

        if cue_id and self.face_tracks.is_done(cue_id):
            # Audio for a cue that already played out silently (synthesis
            # beat the audio_wait_s deadline but lost): the performance
            # happened, don't replay it as a bare audio cue.
            rospy.logwarn("Cue %s: audio arrived after silent playout; dropping it.",
                          cue_id)
            return

        # Legacy path: SpeechData with no announce (old director, external
        # publishers) becomes a complete cue directly, exactly as in v2.
        self.cue_queue.put(Cue(
            cue_id=cue_id,
            text=msg.text_snippet,
            emoji=msg.emoji,
            duration=msg.duration,
            audio_data=msg.audio_data,
            sample_rate=msg.sample_rate,
            chunk_index=msg.current_chunk_index,
            total_chunks=msg.total_chunks,
        ))

    def _parse_command(self, msg, default_duration):
        data = json.loads(msg.data)
        emoji = data.get("emoji", "")
        text = data.get("text", "")
        duration = float(data.get("duration", default_duration))
        cue_id = data.get("cue_id", "")
        return emoji, text, duration, cue_id

    def face_command_cb(self, msg):
        """Silent face cue. `text` may be emoji, prose, or both in one string."""
        try:
            emoji, text, duration, cue_id = self._parse_command(msg, 1.0)
            if not emoji and not text and not cue_id:
                return
            if not emoji:
                emoji = chunking.find_emoji(text, self.face_lut.keys()) or ""
            expect_track = bool(json.loads(msg.data).get("expect_track", False))
            self.cue_queue.put(Cue(cue_id=cue_id, text=text, emoji=emoji,
                                   duration=duration, arms=False,
                                   expect_track=expect_track))
            rospy.loginfo("Queued face cue: %s%s for %.1fs",
                          emoji, (" '" + text + "'") if text else "", duration)
        except (ValueError, json.JSONDecodeError) as e:
            rospy.logerr("Bad /face/emoji_command payload: %s (%s)", msg.data, e)

    def arm_command_cb(self, msg):
        """Arm cue. `text` may be emoji, prose, or both in one string."""
        try:
            emoji, text, duration, cue_id = self._parse_command(msg, 2.0)
            if not emoji and not text and not cue_id:
                return
            if not emoji:
                emoji = chunking.find_emoji(text, self.arm_lut.keys()) or ""
            expect_track = bool(json.loads(msg.data).get("expect_track", False))
            self.arm_queue.put(ArmCue(cue_id=cue_id, emoji=emoji, text=text,
                                      duration=duration, expect_track=expect_track))
            rospy.loginfo("Queued arm cue: %s%s for %.1fs",
                          emoji, (" '" + text + "'") if text else "", duration)
        except (ValueError, json.JSONDecodeError) as e:
            rospy.logerr("Bad /arm/emoji_command payload: %s (%s)", msg.data, e)

    def face_track_cb(self, msg):
        try:
            self.face_tracks.update(json.loads(msg.data))
        except json.JSONDecodeError as e:
            rospy.logerr("Bad /performance/face_track payload: %s", e)

    def arm_track_cb(self, msg):
        try:
            self.arm_tracks.update(json.loads(msg.data))
        except json.JSONDecodeError as e:
            rospy.logerr("Bad /performance/arm_track payload: %s", e)

    # ─── Track resolution (shared by face & arm channels) ─────────────

    @staticmethod
    def _track_usable(track):
        return bool(track and track["frames"] and track["status"] != "failed")

    def _wait_for_track(self, store, cue_id, label="track", timeout_s=None):
        """
        Bounded wait for an animator track. Returns as soon as the FIRST
        frame streams in (or a terminal failed/lut status) -- not full
        completion; that's the "time to first frame" sync point. Used by
        expect_track gestures (~track_wait_s, patient) and sync-mode TTS
        cues (~sync_wait_s, tighter -- speech shouldn't stall as long).
        """
        timeout_s = self.track_wait_s if timeout_s is None else timeout_s
        deadline = time.time() + timeout_s
        while time.time() < deadline and not rospy.is_shutdown():
            track = store.get(cue_id)
            # status "lut" = animator's explicit "play your own LUT" signal
            if track and (track["frames"] or track["status"] in ("failed", "lut")):
                return track
            rospy.sleep(0.1)
        rospy.logwarn("Timed out waiting %.1fs for %s %s; falling back.",
                      timeout_s, label, cue_id)
        return store.get(cue_id)

    # ─── Face resolution & playback ──────────────────────────────────

    def publish_face_pose(self, pose, step_duration):
        """Publish one expanded full pose to the typed face topics."""
        left, right = pose["eyes"]["left"], pose["eyes"]["right"]
        for key in EYE_KEYS:
            state = EYE_STATE_BY_KEY[key]
            pub = self.face_pubs[state]
            if left[key] == right[key]:
                sides = [("both", left[key])]
            else:
                sides = [("left", left[key]), ("right", right[key])]
            for side, value in sides:
                m = EYE_MSG_BY_STATE[state](**{"eye_side": side, key: value})
                m.duration = step_duration
                pub.publish(m)
        mouth = MouthSine(**pose["mouth"])
        mouth.duration = max(0.05, step_duration)
        self.mouth_pub.publish(mouth)

    def _sleep_slices(self, seconds):
        """Sleep in small slices so shutdown stays responsive."""
        end = time.time() + seconds
        while not rospy.is_shutdown() and time.time() < end:
            rospy.sleep(min(0.05, max(0.0, end - time.time())))

    def play_channel_for_cue(self, ch, cue_id, emoji, duration,
                             expect_track=False, wait_timeout_s=None):
        """
        Unified per-cue frame pacing for one channel (face or arms) -- the
        near-identical twin loop bodies of v2 merged, minus the LUT
        cold-open/switch dance.

        Plays whichever single source resolves for the cue:
        - the animator track (frames may still be streaming in), or
        - the local LUT copy, when the animator answers status="lut", the
          cascade failed, the cue is a legacy no-cue_id command, or no
          track message at all shows up by half the cue (animator down --
          the LUT must survive that), or
        - nothing (hold the last pose; always consume the cue duration).

        Live timeline fudging: every iteration re-estimates the remaining
        frame count from what has arrived (complete tracks are exact;
        in-flight streams use a mid-sized guess) and re-paces the remaining
        frames over the remaining cue time, so the timeline continuously
        re-stretches in place as new information lands.
        """
        store = ch["store"]
        track = store.get(cue_id) if cue_id else None
        if expect_track and not self._track_usable(track):
            track = self._wait_for_track(store, cue_id, label=ch["label"] + " track",
                                         timeout_s=wait_timeout_s)

        t0 = time.time()
        t_end = t0 + max(0.1, duration)

        mode = None  # None -> undecided, "track" / "lut" / "idle"
        expander = None
        frames_list = None  # expanded poses ("lut" mode)
        played = 0

        while not rospy.is_shutdown():
            now = time.time()
            if now >= t_end:
                break

            if mode is None:
                track = store.get(cue_id) if cue_id else None
                if self._track_usable(track):
                    mode = "track"
                    expander = ch["expander"]()
                    rospy.loginfo(
                        "Cue %s: %s from %s (join at %d%%)",
                        cue_id, ch["label"], track.get("source") or "animator",
                        int(100 * (now - t0) / (t_end - t0)))
                else:
                    status = (track or {}).get("status", "")
                    # A cue with a cue_id normally gets *some* track from the
                    # animator cascade. Stop believing that once the animator
                    # answered terminally (lut/failed) or stayed completely
                    # silent through half the cue (node down/overloaded).
                    track_expected = bool(cue_id) and status not in ("lut", "failed", "none")
                    if track_expected and (now - t0) < 0.5 * (t_end - t0):
                        rospy.sleep(0.05)  # hold pose; track still coming
                        continue
                    if track_expected:
                        rospy.logwarn(
                            "Cue %s: no %s track by half the cue; falling back to LUT.",
                            cue_id, ch["label"])
                    if emoji and emoji in ch["lut"]:
                        mode = "lut"
                        frames_list = ch["expand"](ch["lut"][emoji]["frames"])
                    else:
                        mode = "idle"
                        if not cue_id and (emoji or ch["label"] == "face"):
                            rospy.logwarn_throttle(
                                5, "No %s animation available for '%s'.",
                                ch["label"], emoji)

            if mode == "track":
                track = store.get(cue_id) or track
                frames = track["frames"] if track else []
                if played < len(frames):
                    if track.get("status") == "complete":
                        est_total = len(frames)
                    else:
                        # stream in flight: assume a mid-sized sequence so
                        # early frames don't hog the whole cue
                        est_total = min(ch["max_frames"],
                                        max(len(frames) + 2, ch["mid_guess"]))
                    step = max(0.05, (t_end - now) / max(1, est_total - played))
                    pose = expander.feed(frames[played])
                    played += 1
                    if pose:
                        ch["publish"](pose, step)
                    self._sleep_slices(min(step, t_end - time.time()))
                else:
                    # stream stall or all frames shown: hold last pose
                    rospy.sleep(0.05)
            elif mode == "lut":
                if played < len(frames_list):
                    step = max(0.05, (t_end - now) / max(1, len(frames_list) - played))
                    ch["publish"](frames_list[played], step)
                    played += 1
                    self._sleep_slices(min(step, t_end - time.time()))
                else:
                    rospy.sleep(0.05)
            else:
                # nothing to show; idle out the duration holding last pose
                rospy.sleep(0.05)

    def play_face_for_cue(self, cue):
        self.play_channel_for_cue(
            self.face_channel, cue.cue_id, cue.emoji, cue.duration,
            expect_track=cue.expect_track, wait_timeout_s=cue.wait_timeout_s)

    # ─── Arm channel ─────────────────────────────────────────────────

    def arm_channel_loop(self):
        while not rospy.is_shutdown():
            try:
                arm_cue = self.arm_queue.get(timeout=0.25)
            except Empty:
                continue
            try:
                self.play_arms_for_cue(arm_cue)
            finally:
                if arm_cue.done_event is not None:
                    arm_cue.done_event.set()

    def publish_arm_pose(self, pose):
        """Publish one expanded full arm pose to /arm/command (joint1/joint2 wire names)."""
        left, right = pose["arms"]["left"], pose["arms"]["right"]
        sides = [("both", left)] if left == right else [("left", left), ("right", right)]
        for side, p in sides:
            self.arm_pub.publish(ArmPose(
                side=side, joint1=p["shoulder_roll"], joint2=p["shoulder_pitch"], wrist=p["wrist"]))

    def play_arms_for_cue(self, arm_cue):
        self.play_channel_for_cue(
            self.arm_channel, arm_cue.cue_id, arm_cue.emoji, arm_cue.duration,
            expect_track=arm_cue.expect_track, wait_timeout_s=arm_cue.wait_timeout_s)

    # ─── Audio ───────────────────────────────────────────────────────

    def play_audio(self, audio_data, sample_rate):
        try:
            if sample_rate <= 0:
                sample_rate = 22050
            self.is_speaking_pub.publish(Bool(data=True))
            audio_array = np.array(audio_data, dtype=np.int16)
            sd.play(audio_array, samplerate=sample_rate)
            sd.wait()
        except Exception as e:
            rospy.logerr("Error playing audio: %s", e)

    # ─── Cue execution ───────────────────────────────────────────────

    def _first_pose(self, ch, cue_id, emoji):
        """First playable pose for a channel: track frame 1, else LUT frame 1."""
        track = ch["store"].get(cue_id) if cue_id else None
        if self._track_usable(track):
            return ch["expander"]().feed(track["frames"][0])
        if emoji and emoji in ch["lut"]:
            poses = ch["expand"](ch["lut"][emoji]["frames"])
            return poses[0] if poses else None
        return None

    def _stage_first_frames(self, cue, staged):
        """
        Pre-speech staging (fudge-contract rule 2): while this cue waits for
        its audio, pose the first face frame and first arm frame from
        whichever source the cascade has already delivered -- a held pose,
        an actor hitting the mark before the curtain. Only the first frame;
        frame 2+ is gated on audio actually starting. Channels that had
        nothing available are retried on the next wait tick.
        """
        if cue.face and not staged["face"]:
            pose = self._first_pose(self.face_channel, cue.cue_id, cue.emoji)
            if pose:
                self.publish_face_pose(pose, 0.4)
                staged["face"] = True
        if cue.arms and not staged["arms"]:
            pose = self._first_pose(self.arm_channel, cue.cue_id, cue.emoji)
            if pose:
                self.publish_arm_pose(pose)
                staged["arms"] = True

    def _await_audio(self, cue):
        """
        Bounded wait for an announced cue's audio, staging first frames in
        the meantime. On timeout the cue plays out silently on est_duration
        (a hung synthesis must not wedge the queue behind it).
        """
        staged = {"face": False, "arms": False}
        deadline = time.time() + self.audio_wait_s
        waited_from = time.time()
        while not rospy.is_shutdown() and not cue.canceled:
            self._stage_first_frames(cue, staged)
            if cue.audio_event.wait(timeout=0.05):
                break
            if time.time() >= deadline:
                rospy.logwarn(
                    "Cue %s: audio still absent after %.1fs; playing silently "
                    "over est %.1fs.", cue.cue_id, self.audio_wait_s, cue.duration)
                break
        waited = time.time() - waited_from
        if waited > 0.25 and cue.audio_event.is_set():
            rospy.loginfo("Cue %s: audio landed after %.2fs staged hold.",
                          cue.cue_id, waited)

    def _wait_for_first_frames(self, cue):
        """
        Sync mode (performance.sync): hold the staged pose until each active
        channel has its first frame (or a terminal lut/failed answer),
        bounded by the cue's wait timeout -- BEFORE audio starts, so speech
        and animation begin together. (v2 placed this wait inside the
        channel loops, after the audio thread was already running, which
        shifted the whole animation window to after the speech.)
        """
        timeout = cue.wait_timeout_s if cue.wait_timeout_s is not None else self.track_wait_s
        deadline = time.time() + timeout

        def ready(store):
            track = store.get(cue.cue_id)
            return bool(track and (track["frames"]
                                   or track["status"] in ("failed", "lut", "none")))

        t0 = time.time()
        while not rospy.is_shutdown() and not cue.canceled:
            if (not cue.face or ready(self.face_tracks)) \
                    and (not cue.arms or ready(self.arm_tracks)):
                if time.time() - t0 > 0.25:
                    rospy.loginfo("Cue %s: first frames ready after %.2fs sync hold.",
                                  cue.cue_id, time.time() - t0)
                return
            if time.time() >= deadline:
                rospy.logwarn("Cue %s: first frames not ready after %.1fs; "
                              "starting anyway.", cue.cue_id, timeout)
                return
            rospy.sleep(0.05)

    def process_cue(self, cue):
        if cue.audio_pending and not cue.audio_event.is_set():
            self._await_audio(cue)
        if cue.audio_pending:
            # Whether audio landed, timed out, or the goal was canceled:
            # this cue no longer waits on the registry.
            with self.pending_lock:
                self.pending_audio.pop(cue.cue_id, None)

        skip_playback = cue.canceled and not len(cue.audio_data)
        has_audio = len(cue.audio_data) > 0

        if not skip_playback and cue.cue_id and cue.expect_track:
            self._wait_for_first_frames(cue)
            # The channels must not wait again: their playback windows are
            # anchored to the audio that starts right now.
            cue.expect_track = False

        if not skip_playback:
            # Playback-time event: this is the moment the cue is actually
            # starting (audio or silent playout) -- captions and Logos-side
            # choreography sync to this, not to synthesis completion.
            self.cue_playing_pub.publish(String(data=json.dumps({
                "cue_id": cue.cue_id,
                "text": cue.text,
                "emoji": cue.emoji,
                "duration": cue.duration,
                "index": cue.chunk_index,
                "total": cue.total_chunks,
                "has_audio": has_audio,
            }, ensure_ascii=False)))

            if has_audio and cue.sample_rate > 0:
                wave = AudioWave()
                wave.data = cue.audio_data
                wave.sample_rate = cue.sample_rate
                self.audio_wave_pub.publish(wave)

            audio_thread = None
            if has_audio:
                sr = cue.sample_rate if cue.sample_rate > 0 else 22050
                audio_thread = threading.Thread(
                    target=self.play_audio, args=(cue.audio_data, sr))
                audio_thread.start()

            # Arms start aligned with the cue, on their own channel. TTS-
            # driven arm cues only wait for a track when this cue opted into
            # sync mode (performance.sync) -- otherwise speech never blocks
            # on generation, same rule as the face channel.
            arm_done = None
            if cue.arms:
                arm_done = threading.Event()
                self.arm_queue.put(ArmCue(cue_id=cue.cue_id, emoji=cue.emoji, text=cue.text,
                                          duration=cue.duration, expect_track=cue.expect_track,
                                          wait_timeout_s=cue.wait_timeout_s,
                                          done_event=arm_done))

            if cue.face:
                self.play_face_for_cue(cue)
            elif cue.duration > 0 and not has_audio:
                rospy.sleep(cue.duration)

            if audio_thread:
                audio_thread.join()

            # Don't yank the arm track out from under a still-playing arm
            # channel (the v2 pop/mark_done race): wait for its confirmation,
            # bounded in case the channel is backed up behind a gesture.
            if arm_done is not None and not arm_done.wait(timeout=3.0):
                rospy.logwarn("Cue %s: arm channel still busy 3s past cue end; "
                              "cleaning up anyway.", cue.cue_id)

        if cue.cue_id:
            self.face_tracks.pop(cue.cue_id)
            self.face_tracks.mark_done(cue.cue_id)
            self.arm_tracks.pop(cue.cue_id)
            self.arm_tracks.mark_done(cue.cue_id)
            self.cue_done_pub.publish(String(data=json.dumps({"cue_id": cue.cue_id})))

        # End of a TTS stream: clear the speaking flag after the last chunk.
        if cue.total_chunks > 0 and cue.chunk_index == cue.total_chunks - 1:
            rospy.loginfo("Speech sequence finished. Clearing is_speaking flag.")
            self.is_speaking_pub.publish(Bool(data=False))

    def run(self):
        while not rospy.is_shutdown():
            try:
                cue = self.cue_queue.get(timeout=0.05)
            except Empty:
                continue
            self.process_cue(cue)


def main():
    try:
        node = PerformanceSequencerNode()
        node.run()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
